name: Build and Push Podman Image to GitHub Container Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Set up Podman
      run: |
        sudo mkdir -p /etc/containers
        echo '[registries.search]' | sudo tee /etc/containers/registries.conf
        echo 'registries = ["ghcr.io"]' | sudo tee -a /etc/containers/registries.conf

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Podman image
      run: sudo podman build -t ghcr.io/${{ github.repository_owner }}/devbox:latest -f ./Containerfile . --log-level=debug

    - name: List Podman images
      run: podman images

    - name: Push Podman image
      run: podman push ghcr.io/${{ github.repository_owner }}/devbox:latest
