name: Build and Push Podman Image to GitHub Container Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Podman image
      run: podman build --no-cache -t ghcr.io/${{ github.repository_owner }}/devbox:latest -f ./Containerfile .

    - name: Push Podman image
      run: podman push ghcr.io/${{ github.repository_owner }}/devbox:latest
